type: task
# The name is optional, if not specified, generated randomly
name: agent-rl-train

# Size of the cluster
nodes: 1

python: "3.11"
nvcc: true


env:
  - HF_TOKEN
  - WANDB_API_KEY
  - WANDB_PROJECT="agent-rl"
  - ACCELERATE_LOG_LEVEL=info

commands:
  - pip install -e '.[retrieve]'
  - pip install bm25s PyStemmer huggingface_hub

  - >
   accelerate launch 
    --config-file configs/zero3.yaml 
    --num-processes 2
    examples/ragent.py train 
    --model 'bdsaglam/Qwen2.5-1.5B-Instruct-ragent-musique'
    --n-env-jobs 1
    --retriever bm25
  
  - huggingface-cli upload --repo-type model bdsaglam/Qwen2.5-1.5B-Instruct-ragent-musique-extended ./outputs/ragent-Qwen2.5-1.5B-Instruct-ragent-musique-musique-grpo
  
resources:
  memory: 40GB..
  gpu:
    # 24GB or more vRAM
    memory: 40GB..80GB
    # One or more GPU
    count: 3
  # Shared memory (for multi-gpu)
  shm_size: 24GB

volumes:
 - /root/.cache:/root/.cache