dataset:
  path: bdsaglam/musique-mini
  name: answerable
  split: validation

model:
  path: /home/baris/repos/verifiers/outputs/Llama-3.1-8B-Instruct-ragent-2
  temperature: 0.5
  top_p: 0.95
  few_shot_prob: 1.0

retriever:
  name: hybrid
  top_k: 1
  mode: 'new'

run: 1
devices: '0'